#! /bin/sh

sxhkd &

## Coloring
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}

xrdb ~/.Xresources
COLOR=$(shuf -n1 -e ~/.colors/*)
SHORTCOLOR=$(echo $COLOR | sed "s@.*/@@")
xrdb -merge $COLOR

getcolors

bspc monitor -d I II III
bspc config focus_follows_pointer true
bspc config border_width 4
bspc config window_gap 5
bspc config normal_border_color "#bbbbbb"
bspc config focused_border_color "#ffffff"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 20
bspc config bottom_padding 15
bspc config right_padding 0
bspc config left_padding 0
feh --bg-center $HOME/Pictures/nitish-meena-37746-unsplash.jpg
compton --config $HOME/.config/compton/compton.conf &

$HOME/.config/polybar/launch.sh
